#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

source ./terraform/infrastructure.env

cd ./terraform/infrastructure

echo "Destorying application infrastructure..."

terraform destroy \
  -var "aws_profile=$AWS_PROFILE"

echo "Complete"