#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

source ./.env

cd ./sample-project

rm -rf ./.git

git init
git checkout -b main
git add .
git commit -m "Push sample project to GitLab"
git remote add origin "ssh://git@gitlab.$GITLAB_DOMAIN:32022/root/sample-project.git" 
git push -u origin main