#!/usr/bin/env bash
set -euo
IFS=$'\n\t'

source ./.env

cd ./sample-project

rm -rf ./.git

find ./ -type f -print0 | xargs -0 sed -i "" "s/__CONTAINER_REGISTRY_USER__/$CONTAINER_REGISTRY_USER/g" || true

git init
git checkout -b main
git add .
git commit -m "Push sample project to GitLab"
git remote add origin "ssh://git@gitlab.$GITLAB_DOMAIN:32022/root/sample-project.git" 
git push -u origin main