stages:
  - Check cache
  - Build Dependencies
  - Test
  - Container Build and Push
  - Deploy
  - Pipeline Complete

variables:
  NODE_ENV: test
  RAILS_ENV: development
  BUNDLE_PATH: vendor

check-cache:
  stage: Check cache
  interruptible: true
  cache:
    - key: cache 
      paths:
        - cache
  script:
    - echo "Starting test build"
    - echo "What's in the cache folder?"
    - mkdir cache || true
    - ls -al cache/
    - |
      if [[ -f "cache/test-file" ]]; then
        echo "cache/test-file exists."
        cat cache/test-file
      else
        echo "creating cache/test-file"
        echo 'I will be cached text' > cache/test-file
        echo "cache/test-file created."
      fi

bundle:
  stage: Build Dependencies
  image: ruby:3.1.2-slim
  interruptible: true
  before_script:
    - apt-get update 
    - apt-get install -y build-essential
  script:
    - bundle config set frozen 'true'
    - bundle install
  artifacts:
    paths:
      - vendor

yarn:
  stage: Build Dependencies
  image: node:16-slim
  interruptible: true
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules

rspec:
  stage: Test
  image: ruby:3.1.2-slim
  interruptible: true
  script:
    - bundle exec rspec
  needs:
    - bundle

jest:
  stage: Test
  image: node:16-slim
  interruptible: true
  parallel: 3
  script:
    - yarn jest --shard "$CI_NODE_INDEX/$CI_NODE_TOTAL" --maxWorkers=1
  needs:
    - yarn

rubocop:
  stage: Test
  image: ruby:3.1.2-slim
  interruptible: true
  script:
    - bundle exec rubocop
  needs:
    - bundle

include:
  - project: root/sample-project
    ref: main
    file: /shared.gitlab-ci.yml

container:build:
  stage: Container Build and Push
  extends: .shared:container:build
  variables:
    DOCKERFILE_PATH: .docker/dockerfiles/Dockerfile
  dependencies: []
  only:
    - main

deploy:
  stage: Deploy
  script:
    - echo 'some deployment command'
  needs:
    - job: container:build
      artifacts: false
  only:
    - main

success:
  stage: Pipeline Complete
  script:
    - echo 'whoop'
  dependencies: []
