AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
