source 'https://rubygems.org'

ruby '3.1.2'

gem 'rails', '~> 7.0'
gem 'bootsnap', require: false
gem 'puma', '~> 5.0'
gem 'sprockets-rails'
gem 'sqlite3', '~> 1.4'
gem 'stimulus-rails'

group :development, :test do
  gem 'amazing_print'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rails-controller-testing'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rubocop'
end

group :development do
  gem 'web-console'
end
