apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k3s-ingress-gitlab
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http, https
spec:
  rules:
    - host: gitlab.{{ .Values.domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gitlab-webservice-default
              port:
                number: 8181
    - host: registry.{{ .Values.domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gitlab-minio-svc
              port:
                number: 5000
    - host: minio.{{ .Values.domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gitlab-registry
              port:
                number: 9000